import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShoppingCart,Menu,X,Minus,Plus,Trash2,ChevronRight,Music2,MapPin,MessageCircle,Heart,Star} from 'lucide-react';
import './styles.css';

const InstagramIcon=({size=24}:{size?:number})=><svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".75" fill="currentColor" stroke="none"/></svg>;
type Category='milk'|'yogurt'|'ice-cream';
type Product={id:string;name:string;category:Category;description:string;image:string;variants?:{name:string;price:number}[];price?:number;toppings?:boolean;badge?:string};
type CartItem={id:string;product:Product;variant?:string;price:number;qty:number;toppings:string[];notes:string};
const WA='628186714333';
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const img=(seed:string)=>`https://images.unsplash.com/${seed}?auto=format&fit=crop&w=900&q=82`;
const products:Product[]=[
{id:'banana',name:'Susu Murni Pisang',category:'milk',description:'Susu murni creamy dengan rasa pisang yang lembut.',image:img('photo-1572449043416-55f7e9f14a02'),variants:[{name:'250ml',price:10000},{name:'330ml',price:13000},{name:'500ml',price:16000}]},
{id:'strawberry',name:'Susu Murni Strawberry',category:'milk',description:'Susu murni creamy dengan strawberry yang fresh.',image:img('photo-1579954115545-a95591f28bfc'),variants:[{name:'250ml',price:10000},{name:'330ml',price:13000},{name:'500ml',price:16000}],badge:'Favorite'},
{id:'chocolate',name:'Susu Murni Chocolate',category:'milk',description:'Perpaduan susu murni dan chocolate yang rich.',image:img('photo-1578985545062-69928b1d9587'),variants:[{name:'250ml',price:10000},{name:'330ml',price:13000},{name:'500ml',price:16000}]},
{id:'matcha',name:'Susu Murni Matcha',category:'milk',description:'Creamy milk dengan aroma matcha yang smooth.',image:img('photo-1556679343-c7306c1976bc'),variants:[{name:'250ml',price:10000},{name:'330ml',price:13000},{name:'500ml',price:16000}]},
{id:'taro',name:'Susu Murni Taro',category:'milk',description:'Rasa taro creamy, manis, dan comforting.',image:img('photo-1579954115545-a95591f28bfc'),variants:[{name:'250ml',price:10000},{name:'330ml',price:13000},{name:'500ml',price:16000}]},
{id:'mango',name:'Susu Murni Mangga',category:'milk',description:'Milk creamy berpadu rasa mangga yang cerah.',image:img('photo-1553279768-865429fa0078'),variants:[{name:'250ml',price:10000},{name:'330ml',price:13000},{name:'500ml',price:16000}]},
{id:'plain',name:'Susu Murni Plain',category:'milk',description:'Susu murni original yang fresh dan creamy.',image:img('photo-1550583724-b2692b85b150'),variants:[{name:'250ml',price:9000},{name:'330ml',price:12000},{name:'500ml',price:15000}]},
{id:'liter',name:'Susu Murni Plain 1 Liter',category:'milk',description:'Ukuran 1 liter untuk dinikmati bersama.',image:img('photo-1550583724-b2692b85b150'),variants:[{name:'1 Liter',price:18000}]},
...['Original','Chocolate','Strawberry','Mangga'].map((x,i)=>({id:`y-${i}`,name:`Yogurt ${x}`,category:'yogurt' as Category,description:'Yogurt creamy dan fresh untuk mood apa saja.',image:img(['photo-1488477181946-6428a0291777','photo-1578985545062-69928b1d9587','photo-1579954115545-a95591f28bfc','photo-1553279768-865429fa0078'][i]),price:8000})),
...['Vanilla + Coklat + Strawberry','Vanilla + Coklat','Vanilla + Strawberry','Coklat + Strawberry','Vanilla','Chocolate','Strawberry'].map((x,i)=>({id:`ice-${i}`,name:`Ice Cream ${x}`,category:'ice-cream' as Category,description:'Ice cream lembut yang siap dikreasikan dengan topping.',image:img(['photo-1563805042-7684c019e11a','photo-1578985545062-69928b1d9587','photo-1579954115545-a95591f28bfc'][i%3]),price:8000,toppings:true,badge:i===0?'Best Seller':undefined}))
];
const free=['Chocochips','Rainbow Chips','Oreo Crumble','Caramel Crumble','Ceres','Rainbow Ceres','Sprinkle','Choco Crunch'];
const paid=[['Silverqueen',3000],['Chocolate Cadbury',3000],['Almond',2000],['Mete',2000],['Kismis',2000]] as const;
function App(){
 const [cat,setCat]=useState<'all'|Category>('all'); const [cart,setCart]=useState<CartItem[]>([]); const [modal,setModal]=useState<Product|null>(null); const [drawer,setDrawer]=useState(false); const [mobile,setMobile]=useState(false); const [toast,setToast]=useState(''); const [selected,setSelected]=useState(''); const [qty,setQty]=useState(1); const [tops,setTops]=useState<string[]>([]); const [notes,setNotes]=useState('');
 useEffect(()=>{const raw=localStorage.getItem('moobun-cart');if(raw)try{setCart(JSON.parse(raw))}catch{}},[]); useEffect(()=>localStorage.setItem('moobun-cart',JSON.stringify(cart)),[cart]);
 const visible=useMemo(()=>cat==='all'?products:products.filter(p=>p.category===cat),[cat]); const total=cart.reduce((s,i)=>s+i.price*i.qty,0); const count=cart.reduce((s,i)=>s+i.qty,0);
 const open=(p:Product)=>{setModal(p);setSelected(p.variants?.[0]?.name||'');setQty(1);setTops([]);setNotes('')};
 const add=()=>{if(!modal)return; const base=modal.variants?.find(v=>v.name===selected)?.price??modal.price??0; const extra=tops.reduce((s,t)=>{const f=paid.find(x=>x[0]===t);return s+(f?.[1]??0)},0); const key=`${modal.id}|${selected}|${tops.join(',')}|${notes}`;setCart(c=>{const hit=c.find(x=>x.id===key);return hit?c.map(x=>x.id===key?{...x,qty:x.qty+qty}:{...x}):[...c,{id:key,product:modal,variant:selected,price:base+extra,qty,toppings:tops,notes}]});setModal(null);setToast(`Yay! ${modal.name} masuk keranjang 🥛💕`);setTimeout(()=>setToast(''),2400)};
 const checkout=()=>{const lines=cart.map((x,i)=>`${i+1}. ${x.product.name}${x.variant?' '+x.variant:''}${x.toppings.length?' + '+x.toppings.join(', '):''} x${x.qty} — ${money(x.price*x.qty)}`).join('\n'); const msg=`Halo MOOBUN 👋\n\nSaya ingin memesan:\n\n${lines}\n\nSubtotal: ${money(total)}\n\nNama:\nAlamat:\nCatatan:\n\nTerima kasih.`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank')};
 return <><header className="nav"><a className="logo" href="#home">MOO<span>BUN</span><small>fresh mood.</small></a><nav>{[['Home','#home'],['Menu','#menu'],['Promo','#promo'],['Cara Order','#order'],['Kemitraan','#partner'],['Tentang','#about'],['Kontak','#contact']].map(([t,h])=><a key={h} href={h}>{t}</a>)}</nav><button className="orderBtn" onClick={()=>setDrawer(true)}><ShoppingCart size={18}/> Order Sekarang {count>0&&<b>{count}</b>}</button><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>{mobile&&<div className="mobileNav">{[['Home','#home'],['Menu','#menu'],['Promo','#promo'],['Cara Order','#order'],['Kemitraan','#partner'],['Tentang','#about'],['Kontak','#contact']].map(([t,h])=><a onClick={()=>setMobile(false)} key={h} href={h}>{t}</a>)}</div>}
 <main>
 <section id="home" className="hero"><div className="blob"></div><div className="heroCopy"><span className="eyebrow">🥛 FRESH MILK • FRESH DESSERT • GOOD MOOD</span><h1>Fresh Milk,<br/><em>Fresh Mood.</em> 🥛💕</h1><p>Susu murni creamy, yogurt segar, dan dessert favorit yang siap bikin harimu lebih manis.</p><div className="heroCta"><a href="#menu" className="primary">Lihat Menu <ChevronRight/></a><button className="secondary" onClick={()=>setDrawer(true)}>Pesan Sekarang</button></div><div className="trust"><span><Star/> 100% Good Mood</span><span><Heart/> Made Fresh</span></div></div><div className="heroVisual"><div className="ring"></div><div className="milkCard"><div className="can">🥛</div><strong>MOOBUN</strong><small>fresh milk</small></div><div className="mini mini1">🍓</div><div className="mini mini2">🍦</div><div className="cow">🐮<i>moo!</i></div></div></section>
 <section className="intro section"><div className="sectionHead"><span className="kicker">WHY MOOBUN?</span><h2>Good Fresh Milk<br/><em>Good Mood.</em></h2><p>MOOBUN menghadirkan susu murni dan dessert dengan rasa creamy, fresh, dan menyenangkan.</p></div><div className="features">{[['🥛','Fresh Milk','Susu murni dengan berbagai pilihan rasa.'],['🍦','Sweet Dessert','Dessert creamy dengan topping favorit.'],['💕','Made With Mood','Dibuat untuk menghadirkan good mood.']].map(x=><article className="feature" key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section id="menu" className="section menu"><div className="sectionHead center"><span className="kicker">OUR MENU</span><h2>Pick Your <em>Favorite</em> 🥛</h2><p>Semua yang kamu butuhkan untuk mood yang lebih baik.</p></div><div className="tabs">{[['all','Semua'],['milk','Susu Murni'],['yogurt','Yogurt'],['ice-cream','Ice Cream']].map(([v,t])=><button className={cat===v?'active':''} onClick={()=>setCat(v as any)} key={v}>{t}</button>)}</div><div className="grid">{visible.map(p=><ProductCard p={p} onAdd={()=>open(p)} onDetail={()=>open(p)} key={p.id}/>)}</div></section>
 <section className="topping section"><div><span className="kicker">DESSERT BAR</span><h2>Make Your Own<br/><em>Dessert ✨</em></h2><p>Pilih ice cream favoritmu, lalu bebas berkreasi. <b>FREE 3 TOPPING</b> untuk setiap pembelian ice cream.</p><div className="topList">{free.slice(0,6).map(x=><span key={x}>✓ {x}</span>)}</div><a href="#menu" className="primary">Create My Dessert <ChevronRight/></a></div><div className="dessertVisual"><div className="scoop">🍨</div><div className="sprinkles">✦ · ✧ · ✦ · ✧</div><div className="cowSmall">🐮</div></div></section>
 <section id="promo" className="section"><div className="sectionHead center"><span className="kicker">GOOD DEALS</span><h2>Promo MOOBUN <em>🎉</em></h2></div><div className="promos">{[['GOOD MOOD COMBO','Mix your favorite milk & dessert.','💗'],['FREE 3 TOPPING','Setiap pembelian Ice Cream.','🍦'],['FRESH DELIVERY','Free ongkir area Talun dan sekitarnya.','🛵']].map(p=><article className="promo" key={p[0]}><span>{p[2]}</span><small>LIMITED PROMO</small><h3>{p[0]}</h3><p>{p[1]}</p><button onClick={()=>setDrawer(true)}>Order Now <ChevronRight/></button></article>)}</div></section>
 <section id="order" className="section steps"><div className="sectionHead center"><span className="kicker">HOW TO ORDER</span><h2>Order Semudah <em>1, 2, 3!</em></h2></div><div className="stepGrid">{[['01','Pilih Menu','Pilih susu, yogurt, atau ice cream favoritmu.'],['02','Atur Pesanan','Pilih ukuran, topping, jumlah, dan catatan.'],['03','Checkout','Kirim pesanan melalui WhatsApp.'],['04','Tunggu & Nikmati','Pesanan diproses dan dikirim ke tempatmu.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
 <section id="partner" className="section partner"><div className="partnerCopy"><span className="kicker">PARTNERSHIP</span><h2>Let's Grow<br/><em>Together 🤝</em></h2><p>Punya usaha, toko, kantin, cafe, atau ingin menjadi reseller? Mari tumbuh bersama MOOBUN.</p><a className="primary" href={`https://wa.me/${WA}?text=${encodeURIComponent('Halo MOOBUN, saya tertarik mengajukan kerja sama.')}`} target="_blank">Ajukan Kerja Sama <MessageCircle/></a></div><div className="partnerCards">{[['Reseller','Untuk kamu yang ingin menjual kembali produk MOOBUN.'],['Titip Jual','Untuk toko, kantin, warung, atau outlet.'],['Partnership','Kerja sama bisnis untuk pengembangan area.']].map(x=><article key={x[0]}><span>♡</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
 <section id="about" className="section about"><div className="aboutCow">🐮<span>moo!</span></div><div><span className="kicker">ABOUT MOOBUN</span><h2>Fresh. Creamy.<br/><em>Friendly.</em></h2><p>MOOBUN adalah kedai susu murni dan dessert yang menghadirkan produk fresh, creamy, dan affordable untuk menemani hari-hari kamu.</p><div className="chips"><span>Fresh</span><span>Creamy</span><span>Affordable</span><span>Cute</span><span>Friendly</span></div></div></section>
 <section id="contact" className="section contact"><div className="sectionHead"><span className="kicker">FIND US</span><h2>Let's Moo! <em>🐮💗</em></h2><p>Rumah Produksi MOOBUN siap melayani pesananmu.</p></div><div className="contactGrid"><a href={`https://wa.me/${WA}`}><MessageCircle/><small>WHATSAPP</small><strong>08186714333</strong></a><a href="mailto:yunarparts@gmail.com"><span>✉️</span><small>EMAIL</small><strong>yunarparts@gmail.com</strong></a><a href="https://instagram.com/moobun.id" target="_blank"><InstagramIcon/><small>INSTAGRAM</small><strong>@moobun.id</strong></a><a href="https://maps.google.com/?q=Jl.+Sultan+Ageng+Tirtayasa,+Cempaka+Talun,+Perumahan+Green+Kedaton+Blok+C+No.+2" target="_blank"><MapPin/><small>LOCATION</small><strong>Green Kedaton Blok C No. 2</strong></a></div><div className="apps"><h3>Pesan MOOBUN di Platform Favoritmu</h3><div><button>GrabFood</button><button>ShopeeFood</button><button>GoFood</button></div></div></section>
 </main><footer><div className="footerLogo">MOO<span>BUN</span><small>Good Fresh Milk · Good Mood</small></div><div className="footerLinks">{['Home','Menu','Promo','Cara Order','Kemitraan','Kontak'].map(x=><a href={'#'+x.toLowerCase().replace(' ','-')} key={x}>{x}</a>)}</div><div className="social"><a href="https://instagram.com/moobun.id"><InstagramIcon/></a><a href="https://tiktok.com/@moobun.id"><Music2/></a></div><p>© 2026 MOOBUN. All rights reserved.</p></footer>
 {count>0&&<button className="mobileCart" onClick={()=>setDrawer(true)}><ShoppingCart/> Pesan Sekarang <b>{count} · {money(total)}</b></button>}
 {modal&&<div className="overlay" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button><img src={modal.image}/><div className="modalBody"><span className="kicker">{modal.category==='milk'?'SUSU MURNI':modal.category==='yogurt'?'YOGURT':'ICE CREAM'}</span><h2>{modal.name}</h2><p>{modal.description}</p>{modal.variants&&<div><label>Size</label><div className="variantRow">{modal.variants.map(v=><button className={selected===v.name?'selected':''} onClick={()=>setSelected(v.name)} key={v.name}>{v.name}<small>{money(v.price)}</small></button>)}</div></div>}{modal.toppings&&<div><label>Topping <small>{tops.length}/3 free</small></label><div className="toppingPick">{[...free,...paid.map(x=>x[0])].map(t=><button className={tops.includes(t)?'selected':''} onClick={()=>setTops(s=>s.includes(t)?s.filter(x=>x!==t):(s.length<3||paid.some(x=>x[0]===t))?[...s,t]:s)} key={t}>{t}{paid.some(x=>x[0]===t)&&<small>+{money(paid.find(x=>x[0]===t)![1])}</small>}</button>)}</div></div>}<label>Jumlah</label><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><b>{qty}</b><button onClick={()=>setQty(qty+1)}><Plus/></button></div><label>Catatan</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Contoh: less sweet"/><button className="primary full" onClick={add}>Tambah ke Keranjang — {money(((modal.variants?.find(v=>v.name===selected)?.price??modal.price??0)+tops.reduce((s,t)=>s+(paid.find(x=>x[0]===t)?.[1]??0),0))*qty)}</button></div></div></div>}
 {drawer&&<div className="overlay" onClick={()=>setDrawer(false)}><aside className="cart" onClick={e=>e.stopPropagation()}><div className="cartHead"><h2>Keranjang 🛒</h2><button onClick={()=>setDrawer(false)}><X/></button></div>{cart.length===0?<div className="empty"><div>🥛</div><h3>Keranjang masih kosong</h3><p>Yuk pilih menu favoritmu.</p><a href="#menu" onClick={()=>setDrawer(false)} className="primary">Lihat Menu</a></div>:<><div className="cartItems">{cart.map(x=><div className="cartItem" key={x.id}><img src={x.product.image}/><div><h4>{x.product.name}</h4><small>{x.variant}{x.toppings.length?' · '+x.toppings.join(', '):''}</small><strong>{money(x.price*x.qty)}</strong><div className="line"><button onClick={()=>setCart(c=>c.map(i=>i.id===x.id?{...i,qty:Math.max(1,i.qty-1)}:i))}><Minus/></button><b>{x.qty}</b><button onClick={()=>setCart(c=>c.map(i=>i.id===x.id?{...i,qty:i.qty+1}:i))}><Plus/></button><button className="remove" onClick={()=>setCart(c=>c.filter(i=>i.id!==x.id))}><Trash2/></button></div></div></div>)}</div><div className="cartFoot"><div><span>Subtotal</span><strong>{money(total)}</strong></div><button className="primary full" onClick={checkout}>Pesan via WhatsApp <MessageCircle/></button><small>Delivery order only · Free ongkir area Talun dan sekitarnya.</small></div></>}</aside></div>}
 {toast&&<div className="toast">{toast}</div>}
 </>}
function ProductCard({p,onAdd,onDetail}:{p:Product;onAdd:()=>void;onDetail:()=>void}){return <article className="product"><div className="photo"><img src={p.image}/>{p.badge&&<span>{p.badge}</span>}<button onClick={onDetail}>Detail</button></div><div className="productBody"><div><small>{p.category==='milk'?'SUSU MURNI':p.category==='yogurt'?'YOGURT':'ICE CREAM'}</small><h3>{p.name}</h3></div><p>{p.description}</p><div className="priceRow"><strong>{money(p.variants?.[0].price??p.price??0)}</strong><button onClick={onAdd}><Plus size={18}/></button></div></div></article>}
createRoot(document.getElementById('root')!).render(<App/>);
